name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'
      - run: dotnet pack -p:PackAsTool=true -p:ReadyToRun=false -p:PublishTrimmed=false -c release Breacher/Breacher.csproj
      - name: Nuget Push
        env:
          token: ${{ secrets.nuget_token }}
        run: dotnet nuget push dist/breacher*.nupkg --api-key "$token"